name: Build windows app

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'pccclient/**'
      - '.github/workflows/build-windows.yaml'
# https://intothelambda.com/blog/github-actions-with-paths/
defaults:
  run:
    working-directory: pccclient

# https://blog.dalt.me/3249
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: flutter build windows
      - name: Copy runtime dll
        run: "copy C:\\Windows\\System32\\vcruntime140_1.dll .\\build\\windows\\runner\\Release"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: pccclient/build/windows/runner/Release
